# Generated by Django 6.0.4 on 2026-04-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Describe the exoplanet model or tool.')),
                ('repository_url', models.URLField(max_length=500, verbose_name='GitHub Link')),
                ('category', models.CharField(choices=[('SPEC', 'Spectroscopy'), ('ATM', 'Atmospheric Modeling'), ('SIM', 'Observation Simulation')], default='SIM', max_length=4)),
            ],
        ),
    ]
