# Generated by Django 5.2.13 on 2026-04-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scientifictool",
            name="category",
            field=models.CharField(
                choices=[
                    ("SPEC", "Spectroscopy"),
                    ("ATM", "Atmospheric Modeling"),
                    ("SIM", "Observation Simulation"),
                    ("DA", "Data Analysis"),
                ],
                default="SIM",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="scientifictool",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
